### ISSUE TITLE
become_user unset?

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/ansible-role-quantum-espresso#5]
Shouldn't there be a `become_user: "{{ root_user }}"` inside the first task of the role (and a definition of this in the defaults/main.yml? This is there in the role for Wannier90 but not here, and if I try to run this role from (an earlier version of) the Quantum Mobile (modified from 19.03) this role fails because it does not become `root` but it remains `max`.

Before changing, though, I'd like to understand better how it works (also because I'm using an older QMobile version - btw, shouldn't we pin the versions of the roles rather than use 'master'? If I now want to rebuild an old version of Quantum Mobile, I would anyway get the most recent roles, which is not what we want, right?)

**Comment by ltalirz** [comment]
We're currently in a transition phase, where I'm moving away entirely from the `become_user` for "simulation code roles" (step 1 here: https://github.com/marvel-nccr/quantum-mobile/issues/96)

The develop branch already uses fixed versions: https://github.com/marvel-nccr/quantum-mobile/blob/develop/requirements.yml

**Comment by ltalirz** [comment]
Just to mention also that I'm bumping the major version number for this transition, i.e. v0.1.2 of the quantumespresso role still has the `become_user`

**Comment by giovannipizzi** [comment]
ok thanks, so I'll close this for now
